init_registers = torch.cuda.IntTensor([0,1,0])
first_arg = torch.cuda.IntTensor([1,0,2])
second_arg = torch.cuda.IntTensor([2,1,2])
target = torch.cuda.IntTensor([1,2,2])
instruction = torch.cuda.IntTensor([1,9,0])